# Generated by Django 3.2 on 2021-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app2', '0002_alter_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.TextField(),
        ),
    ]
