# Generated by Django 2.2.4 on 2021-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
